language: go
go:
  - 1.2
  - 1.3
  - release

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/tools/godep
  - godep restore
  - godep get

matrix:
  allow_failures:
    - go: 1.2
    - go: 1.3
    - go: release

script:
 - go test -v ./...